### ISSUE TITLE
*exercinte

### ISSUE THREAD

**Issue by meixome** [meixome/hunspell-gl#147]
Revisar 

exercer/310,311,312,410,411,412 po:verbo ts:transitiva / intransitiva VOLG t i al:exércer
exércer/666,315,415 st:exercer ts:alomorfo exercer transitiva / intransitiva

**Comment by Gallaecio** [comment]
Entendo que «exercinte» pode chegar a ser unha palabra válida en casos nos que se fale a unha cousa prsonificándoa. Non teño claro que debamos marcala como incorrecta.

**Comment by Gallaecio** [comment]
Suxiro pechar este problema e xestionar a súa solución como parte de #226.
