### ISSUE TITLE
error

### ISSUE THREAD

**Issue by meixome** [meixome/hunspell-gl#186]
Dáo como correcto ao considerarse latinismo...

mentres que é típico como castelanismo

*error > erro

**Comment by meixome** [comment]
Pois cabe a posibilidade de propoñer erro como suxestión en nas regras rep

**Comment by Gallaecio** [comment]
¿Marcamos entón o latinismo «error» como incorrecto? Senón a regra de substitución non vai servir de nada.

**Comment by meixome** [comment]
Si, claro

**Comment by meixome** [comment]
Desde logo, o da RAG máis ca clarificar, difumina...

Está claro que se prefire «erro» pero dáse «error» con correcta.
