### ISSUE TITLE
amosase, xerase

### ISSUE THREAD

**Issue by meixome** [meixome/hunspell-gl#188]
Non distingue se falta o acento ou non

amosase/amósase
xerase/xérase

**Comment by Gallaecio** [comment]
Non teño claro que nos interese marcar amosase, xerase e procedese como incorrectas, pero se queremos considerar facelo, creo que isto debería facerse como parte de #226 e pechar este problema.

**Comment by meixome** [comment]
Si, é o mesmo asunto. Vai para #226
