### ISSUE TITLE
inclusion/upgrate in libreoffice-dictionaries

### ISSUE THREAD

**Issue by mapreri** [meixome/hunspell-gl#201]
Dear hunspell-gl maintainer,

libreoffice-dictionaries provides a copy of hunspell-gl which (according to [this bug](https://bugs.documentfoundation.org/show_bug.cgi?id=56130)) is coming from yours [meixome/hunspell-gl-volga](https://github.com/meixome/hunspell-gl-volga).

Some months ago I was looking at updating what we currently have [in debian](https://packages.debian.org/source/sid/hunspell-gl-es) as well as what's embedded in libreoffice-dictionaries.

After looking a bit it looked like we could have updated what's in LO-dicts using what's in this repository (see [this other bug](https://bugs.documentfoundation.org/show_bug.cgi?id=99826)), but digging some more revealed that what's currently there and coming from hunspell-gl-volga contained about 4000 more words.

Could you please shed some light on what's the difference between the 2 dictionaries, and what one should be distributed with libreoffice, and which one is more up-to-date?

Thanks in advance.

**Comment by meixome** [comment]
Please, use hunspell-gl only for future.
After refactoring the system for compiling galician dictirionaries, versión hunspell-gl-volg is not optimal.
The "basic" versión must be compiled without flags, only scons

**Comment by mapreri** [comment]
Ok, so could you please write in https://bugs.documentfoundation.org/show_bug.cgi?id=99826 (or open a new bug in that bug tracker) what LO should do?

If I understand correctly what you have written we should change the dict there (which is hunspell-gl-volga) with the non-volga variant here, right?

**Comment by Gallaecio** [comment]
Yes, that’s right.

VOLGa is the name of a compilation of valid, tolerated and invalid words by the main language authority for Galician: RAG. RAG eventually created an online dictionary (https://academia.gal/dicionario). While the VOLGa vocabulary remains online (https://academia.gal/recursos-volg), it is frozen, and only the dictionary is updated.
