### ISSUE TITLE
Descarga da última versión

### ISSUE THREAD

**Issue by barcia** [meixome/hunspell-gl#203]
Ola boas! pregúntome onde podo descargar a última versión. No arquivo `/build` do repositorio pon que se descarga dende SourceForge, pero en SourceForge por que a última versión é do 2014 e no repositorio vexo que hai commits do 2017.

Gracias de antemán.

**Comment by Gallaecio** [comment]
Podes construír a última versión seguindo as instrucións de https://github.com/meixome/hunspell-gl/blob/master/install-gl.txt
