### ISSUE TITLE
Publicar os arquivos compilados na sección de releases

### ISSUE THREAD

**Issue by barcia** [meixome/hunspell-gl#254]
Vexo que tendes unha [_pre-release_](https://github.com/meixome/hunspell-gl/releases) da nova versión xa publicada. Pregúntome se sería posible, unha vez se publique a _release_, publicar tamén nos _assets_ os arquivos completos xa compilados e listos para **descargar e instalar**, pois resulta moi práctico telos xa ahí, **é un lugar creado para iso**, e ademáis non todo o mundo ten os coñecementos para facelo pola súa conta.

**Comment by meixome** [comment]
Salvante que aparezan problemas non detectados, é unha release (edición) definitiva. 

O problema de publicar as compilacións é o seguinte: reordenamos o código do corrector de modo que se poidan compilar versións dos ficheiros adaptadas a necesidades variables. Así pode crearse unha versión que conteña unicamente o que chamamos módulo da "RAG"  ou que conteña o módulo da RAG e tamén o de achegas da "comunidade" pero que non conteña vocabulario da Wikipedia ou outras fontes. Ademais de cara ao futuro haberá moitos máis módulos temáticos que poden ser de interese para públicos específicos polo que o corrector poderá/deberá compilarse para o público xeral cunha determinada selección de módulos.
Por esa razón cada edición pode ter varias compilacións, especialmente do ficheiro .dic

Sobreentendo isto, acabo de publicar na sección de releases unha compilación con todos os módulos incluídos para facilitar a instalación manual.

De todas maneiras isto é o que facemos tamén na nova publicada no web: http://trasno.gal/2018/07/28/hunspell-para-o-galego-version-18-07-francisco-miras/
