### ISSUE TITLE
Crear version final 18.07

### ISSUE THREAD

**Issue by frandieguez** [meixome/hunspell-gl#265]
Hola,

estou movendo xunto co mantedor orixinal en AUR (ArchLinux User Repository) o paquete de hunspell-gl para ter a última versión 18.07, porén a versión que hay creada é unha pre-release.

Xa temos unha versión do empaquetado actualizada ao novo sistema, máis precisamos que publiquedes a versión final.

Saúdos.

**Comment by meixome** [comment]
Feito, xa está publicada como release
